### ISSUE TITLE
Not working on ARM64

### ISSUE THREAD

**Issue by Vysp3r** [OfficialLambdax/BeamMP-ServerDocker#1]
**Here's the error log**
```
 => [beammp_server internal] load build definition from Dockerfile                                     0.1s
 => => transferring dockerfile: 846B                                                                   0.0s
 => ERROR [beammp_server internal] load metadata for docker.io/library/archlinux:base                  0.6s
------
 > [beammp_server internal] load metadata for docker.io/library/archlinux:base:
------
failed to solve: archlinux:base: failed to resolve source metadata for docker.io/library/archlinux:base: no match for platform in manifest: not found
```

**Comment by Vysp3r** [comment]
Could it be related to the Dockerfile?

**Comment by Vysp3r** [comment]
It's looking like that to me since from the website I can see that archlinux only supports amd64.

Could you look into updating the Dockerfile to use an OS that supports more platforms?

**Comment by Vysp3r** [comment]
Currently testing a modification of your script with debian instead of archlinux so that every platform is supported

**Comment by Vysp3r** [comment]
I was able to make it run on Arm64 and it also reduced the size of your scripts

I will create a PR later today

**Comment by OfficialLambdax** [comment]
I didnt add arm support because i dont have arm devices to test run it on, but im curious about the pr (:

**Comment by Vysp3r** [comment]
I will create a script tonight that will download the latest server version to automate the process a bit more

**Comment by Vysp3r** [comment]
I decided to use https://github.com/RouHim/beammp-container-image instead so I will close this PR.
